### PR TITLE
Gsa 49 create routes server

### LINKED ISSUE #49: refactor: create routes on server side
- create a route folder
- add user route
-add image upload route

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
1. Create express routes for API, image, and user
2. add middleware  for storing and uploading images

## Purpose
Implement express route 

## Learning
https://www.bezkoder.com/node-js-upload-store-images-mongodb/

- from previous project
Closes #49

### CODE REVIEW

**Review by brycejjacks — APPROVED** [review]
* you can move the mongo connection to the db.config.ts page (i also like that name over db.ts lol) 
* middleware is cool but dont delete function with the .single
* dont forget to add the .single back to the image router page

love the initiative to move all this stuff .. what would we be without you

**Comment by brycejjacks** [comment]
lol oops forgot to open blocking conversations .. dont merge until changes are made ill look again after

**Comment by ChelleAmon** [comment]
@brycejjacks @czcarrizales made a few changes.

**Review by brycejjacks — APPROVED** [review]
glad we could build a better understanding together on this .. merging

**Pull request merged**
