### PR TITLE
Gsa 45 display guest player username

### LINKED ISSUE #45: ref(f1): Display guest player username
use socket ID to grab its 6 letter substring and concatenate before 'player'

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
1. add logic to concatenate 'guest_' and substrings of a socket ID
2. Add condition if a substring contains '-' or '_'

## Purpose
Create a unique guest name by concatenating 'guest_' string and substring of socket ID when connected.

## Learning

Closes #45

### CODE REVIEW

**Comment by ChelleAmon** [comment]
I thought of changing some code so I made this PR a draft because of some minor bugs but I decided to keep it and work on other features lol. Sorry for the confusion

**Comment by brycejjacks** [comment]
im going to wait to review this one .. it looks like it has some of the changes from the previous pr .. in not sure if that is because the last one has not been merged? or because this pr requires changes from the previous? or because you simply branched it from another feature brach( not development)... i think waiting until the other is merged might help bring me some clarity.

**Comment by ChelleAmon** [comment]
@brycejjacks you can now review this PR

**Review by brycejjacks — APPROVED** [review]
When i say i dove all the way into regex again with this pr lol .. i know EXACTLY what this regex does... also I personally dont like the underscore concatenated with guest .. i think guest83423 looks better than guest_2303485 .. but of course it is your feat so do your thing.

**Comment by ChelleAmon** [comment]
@brycejjacks Your suggestions are highly valued and upon deep thinking, the changes will be made and you should see them on my next PR! Thanks for the feedback lol!

**Pull request merged**
