### PR TITLE
Gsa 32 create game schema

### LINKED ISSUE #32: Feat(f1): create game schema
- create game schema

### PR DESCRIPTION
**Pull request by ChelleAmon**
## Changes
1. Create a game model
2. Create a game schema

## Learning

Closes #32

### CODE REVIEW

**Review by brycejjacks — APPROVED** [review]
i know i mentioned dropping the pin and type from the from the game model and schema earlier.. but ive thought it through and i _do_ want to drop them for less clutter... i also dont really like changes to the tsconfig page unless i really know what im doing and im not there yet.. im sure there is something that we could be doing in the ts files to fix whatever error that presented. but that is a me thing and ill just take a mental note that that was changed if anything starts trippin. Merge whenever ready.. ill change the model and schema myself if you decide to merge without taking them off.

**Comment by ChelleAmon** [comment]
the tsconfig is updated because I'm getting the issue where it won't let me import any files. Below is the error message I get: 

Screen Shot 2022-03-30 at 1 55 20 PM

But, we can always change the `"importsNotUsedAsValues": "preserve"` in tsconfig if this will create more issues in the future.

**Comment by brycejjacks** [comment]
ok thank you for giving that lil demo. that makes sense, and i am all for that change ... also i know exactly what error that is. and i usually fix it by changing "import mongoose ..." to "import type mongoose". the error is happening because you are not using mongoose as a value but as a type ... cool to see another way to deal with that thanks... im merging

**Comment by ChelleAmon** [comment]
@brycejjacks yeah I also thought of changing it to "import type mongoose" but I was unsure of its effect later. But like you said, if any error occurs later, we'll take mental note of the tsconfig change and I think that will help me better understand this configuration lol

**Pull request merged**
